Update deploy-lambda.yml and Services.csproj to target .NET 9.0 and adjust CDK commands

diff --git a/.github/workflows/deploy-lambda.yml b/.github/workflows/deploy-lambda.yml
--- a/.github/workflows/deploy-lambda.yml
+++ b/.github/workflows/deploy-lambda.yml
@@ -76,19 +76,19 @@ jobs:
           ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
           cdk bootstrap aws://$ACCOUNT_ID/$AWS_REGION --require-approval never
 
-      - name: CDK Synth
-        working-directory: Infra
-        run: |
-          cdk synth --app "dotnet run -c Release --no-build" || (echo "CDK synth failed"; exit 1)
+     # - name: CDK Synth
+     #   working-directory: Infra
+     #   run: |
+     #     cdk synth --app "dotnet run -c Release --no-build" || (echo "CDK synth failed"; exit 1)
 
       - name: CDK Deploy
         working-directory: Infra
         run: |
-          cdk deploy InfraStack --app "dotnet run -c Release --no-build" --require-approval never
+          cdk deploy InfraStack --app "dotnet run -c Release --framework net6.0 --no-build" --require-approval never
           
       - name: CDK Deploy EC2 Stack
         working-directory: Infra
         run: |
           cdk deploy WebApiStack \
-            --app "dotnet run -c Release --no-build" \
+            --app "dotnet run -c Release --framework net9.0 --no-build" \
             --require-approval never    
